#ifndef SANDBOX_UTILS_DECISION_H
#define SANDBOX_UTILS_DECISION_H

enum decision {
    DECISION_ALLOW,
    DECISION_DENY,
    DECISION_UNKNOWN,
    DECISION_ERROR
};

#endif // SANDBOX_UTILS_DECISION_H
